### ISSUE TITLE
[Feature] About iOS ipa release.

### ISSUE THREAD

**Issue by shikiroot** [FoxSensei001/i_iwara#5]
Could add these steps to workflow to publish iOS ipa release. Already tested actions on my fork and ipa file on iPad Pro with latest iPadOS.
```
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get tag
        id: tag
        run: echo "TAG=<$_release_tag>" >> $GITHUB_ENV
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Enable iOS
        run: flutter config --enable-ios
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      - name: Create ipa
        run: |
          mkdir Payload
          mv build/ios/Release-iphoneos/Runner.app Payload
          zip -qr /tmp/i_iwara.ipa Payload
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG}}
          files: /tmp/i_iwara.ipa
```
